services:
  acserver-exporter:
    build: .
    environment:
      - AC_SERVER_HOST=79.137.79.153
      - AC_SERVER_UDP_PORT=9600
      - AC_SERVER_HTTP_PORT=8081
      - METRICS_PORT=9090
    ports:
      - "9090:9090"
    network_mode: host
    stdin_open: true
    tty: true